# Generated by Django 5.2.1 on 2025-05-27 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlmenauChecklistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Ilmenau Checklist Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IlmenauResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('transport', 'Transportation'), ('housing', 'Housing'), ('shopping', 'Shopping'), ('healthcare', 'Healthcare'), ('university', 'University Services'), ('government', 'Government Services'), ('social', 'Social & Recreation'), ('emergency', 'Emergency Contacts')], max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['resource_type', 'order'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='arrival_airport',
            field=models.CharField(blank=True, help_text='Main airports: ERF (Erfurt), LEJ (Leipzig), FRA (Frankfurt)', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='arrival_status',
            field=models.CharField(choices=[('PLANNING', 'Planning to Arrive in Ilmenau'), ('ARRIVED', 'Arrived in Ilmenau')], default='PLANNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='intended_city',
            field=models.CharField(default='Ilmenau', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(choices=[('US', 'United States'), ('IN', 'India'), ('CN', 'China'), ('BR', 'Brazil'), ('TR', 'Turkey'), ('RU', 'Russia'), ('MX', 'Mexico'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('NG', 'Nigeria'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='university',
            field=models.CharField(choices=[('TU_ILMENAU', 'Technical University of Ilmenau'), ('OTHER_ILMENAU', 'Other Institution in Ilmenau')], default='TU_ILMENAU', max_length=100),
        ),
        migrations.CreateModel(
            name='IlmenauChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('helpful_link', models.URLField(blank=True, help_text='Helpful web link for this task')),
                ('link_text', models.CharField(blank=True, help_text='Display text for the link', max_length=100)),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tu_ilmenau_specific', models.BooleanField(default=False, help_text='Only for TU Ilmenau students')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.ilmenauchecklistcategory')),
            ],
            options={
                'verbose_name': 'Ilmenau Checklist Item',
                'verbose_name_plural': 'Ilmenau Checklist Items',
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserChecklistProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="User's personal notes for this item")),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ilmenauchecklistitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_progress_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Checklist Progress',
                'verbose_name_plural': 'User Checklist Progress',
                'unique_together': {('user', 'checklist_item')},
            },
        ),
    ]
